version: '3'
services:
  movies:
    build: reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - api
      - frontend
    restart: always
  frontend:
    build: frontend
    ports:
      - 8081:80
    volumes:
      - frontend:/src
    command: yarn start
  api:
    build: api
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=okteto
      - MONGODB_HOST=mongodb
    ports:
      - 8082:80
    volumes:
      - api:/src
    command: yarn start
    depends_on:
      mongodb:
        condition: service_healthy
  init:
    build: api
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=okteto
      - MONGODB_HOST=mongodb
    command: yarn load
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=okteto
      - MONGODB_ROOT_PASSWORD=adminroot
      - MONGODB_SYSTEM_LOG_VERBOSITY=0
      - MONGODB_DISABLE_SYSTEM_LOG=no
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_ENABLE_DIRECTORY_PER_DB=no
    ports:
      - 27017:27017
    volumes:
      - data:/bitnami/mongodb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  data:
  frontend:
  api:
